DROP SCHEMA scd_test1;
CREATE SCHEMA scd_test1;
USE scd_test1;

DROP TABLE CUSTOMER_DETAILS_DIM;
DROP TABLE CUSTOMER_DETAILS_DIM_STAGE;
  
CREATE TABLE CUSTOMER_DETAILS_DIM(
 CUSTOMER_DIM_SK INT(4) NOT NULL AUTO_INCREMENT,
  CUSTOMER_ID INT(4) NOT NULL,
  CUSTOMER_FIRST_NAME VARCHAR(45) NULL,
  CUSTOMER_LAST_NAME VARCHAR(45) NULL,
  CUSTOMER_ADDRESS VARCHAR(45) NULL,
  PINCODE INT(2) NULL,
  CUSTOMER_DOB DATETIME NULL,
  scd_start DATETIME NULL,
  scd_end DATETIME NULL,
  scd_version INT(2) NULL,
  scd_active TINYINT(1) NULL,
  PRIMARY KEY (CUSTOMER_DIM_SK));
  COMMIT;
 
  
  CREATE TABLE CUSTOMER_DETAILS_DIM_STAGE(
  CUSTOMER_ID INT(4) NOT NULL,
  CUSTOMER_FIRST_NAME VARCHAR(45) NULL,
  CUSTOMER_LAST_NAME VARCHAR(45) NULL,
  CUSTOMER_ADDRESS VARCHAR(45) NULL,
  PINCODE INT(2) NULL,
  CUSTOMER_DOB DATETIME NULL,
  DATE DATETIME NULL,
  scd_start DATETIME NULL,
  scd_end DATETIME NULL,
  scd_version INT(2) NULL,
  scd_active TINYINT(1) NULL);
  COMMIT;
  
  SELECT * FROM CUSTOMER_DETAILS_DIM_STAGE;
  SELECT * FROM CUSTOMER_DETAILS_DIM;
  
  
 